import { NavigationMenu } from '@/components/shared/sidebar/NavigationMenu';
import { SignedIn, SignedOut } from '@clerk/nextjs';
import { Bouncer } from '@components/authentication/Bouncer';
import { Header } from '@components/authentication/Header';
import { SignedOutView } from '@components/authentication/_signed-out/View';
import { SidebarInset, SidebarProvider } from '@repo/ui/components/ui/sidebar';
import FlickeringGrid from '@ui/components/ui/flickering-grid';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import type React from 'react';
import Providers from './providers';

import '@repo/ui/globals.css';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Beem',
  description: 'Generated by @ajay-bhargava',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <div className="relative flex min-h-screen flex-col">
            <Header />
            <div className="flex-1">
              <SignedOut>
                <SignedOutView />
              </SignedOut>
              <SignedIn>
                <SidebarProvider>
                  <div className="flex min-h-screen w-full">
                    <NavigationMenu />
                    <main className="flex-1 overflow-auto w-full">
                      <SidebarInset className="relative w-full">
                        <header className="flex h-16 shrink-0 items-center transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12">
                          {/* Header content for things like breadcrumbs, search, etc., */}
                        </header>
                        <div className="flex flex-1 flex-col gap-4 p-4 pt-0 w-full">
                          {children}
                        </div>
                      </SidebarInset>
                    </main>
                  </div>
                </SidebarProvider>
              </SignedIn>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
