import { SignedIn, SignedOut } from '@clerk/nextjs';
import { Bouncer } from '@components/landing/Bouncer';
import { Header } from '@components/shared/header';
import FlickeringGrid from '@ui/components/ui/flickering-grid';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import type React from 'react';
import Providers from './providers';

import '@repo/ui/globals.css';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Beem',
  description: 'Generated by @ajay-bhargava',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <div className="relative flex min-h-screen flex-col">
            <Header />
            <div className="flex-1">
              <SignedOut>
                <main className="relative min-h-screen flex items-center justify-center">
                  <FlickeringGrid
                    className="absolute -z-10"
                    squareSize={4}
                    gridGap={6}
                    color="#60A5FA"
                    maxOpacity={0.1}
                    flickerChance={0.1}
                  />
                  <div className="size-full flex items-center justify-center">
                    <Bouncer />
                  </div>
                </main>
              </SignedOut>
              <SignedIn>{children}</SignedIn>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
